export enum UserType {
  BRAND = "BRAND",
  INFLUENCER = "INFLUENCER",
  SUPERADMIN = 'SUPERADMIN',
  ADMIN = 'ADMIN'
}

export enum RequestState {
  IDLE = "IDLE",
  LOADING = "LOADING",
  ERROR = "ERROR",
  COMPLETED = "COMPLETED",
}

export enum DemographyType {
  AGE_GENDER = "AGE_GENDER",
  COUNTRY = "COUNTRY",
  CITY = "CITY",
}

export enum ProfileSetupState {
  REGISTERED = 'REGISTERED',
  PROFILE_SETUP = 'PROFILE_SETUP',
  PROFILE_SETUP_COMPLETED = "PROFILE_SETUP_COMPLETED"
}