export enum UserType {
  BRAND = "BRAND",
  INFLUENCER = "INFLUENCER",
  SUPERADMIN = 'SUPERADMIN',
  ADMIN = 'ADMIN'
}

export enum RequestState {
  IDLE = "IDLE",
  LOADING = "LOADING",
  ERROR = "ERROR",
  COMPLETED = "COMPLETED",
}

export enum DemographyType {
  AGE_GENDER = "AGE_GENDER",
  COUNTRY = "COUNTRY",
  CITY = "CITY",
}

export enum PaymentMethod {
  PAYSTACK = "PAYSTACK",
  FLUTTERWAVE = "FLUTTERWAVE",
}

export enum ProfileSetupState {
  REGISTERED = 'REGISTERED',
  INDUSTRY_SELECTED = 'INDUSTRY_SELECTED',
  PROFILE_SETUP = 'PROFILE_SETUP',
  PROFILE_SETUP_COMPLETED = "PROFILE_SETUP_COMPLETED",
  PROFILE_SETUP_COMPLETE = "PROFILE_SETUP_COMPLETE"
}