export default Object.freeze({
  NOTIFICATION_SETTINGS_INFLUENCER: "notification-settings-influencer",
  ADDRESS_DOCUMENTATION_INFLUENCER: "address-documentation-v2",
  ADDRESS_DOCUMENTATION: "address-documentation",
  NOTIFICATION_SETTINGS: "notification-settings",
  PERSONAL_INFORMATION: "personal-information",
  ACCOUNT_DEACTIVATION: "account-deactivation",
  PAYMENT_INFORMATION: "payment-information",
  INDUSTRY_SELECTION: "industry-selection",
  BASIC_INFORMATION: "basic-information",
  BRAND_INFORMATION: "brand-information",
  CONTENT_CATEGORY: "content-category",
  COMPLETE_PROFILE: "complete-profile",
  BASIC_DETAILS: "basic-details",
  EMAIL_VERIFY: "email-verify",
  BANK_DETAILS: "bank-details",
  INFLUENCER: "influencer",
  PASSWORD: "password",
  REVIEW: "review",
  AGENCY: "agency",
});